### PR TITLE
adding missing packages for simulator.qmd

### PR DESCRIPTION
**Pull request by Polarolouis**

### CODE REVIEW

**Comment by astamm** [comment]
The dependencies are already set up for installation in `pr_actions.yml` on the main branch. And {simChef} is pre-installed on the Docker container.

**Comment by astamm** [comment]
However, we should update action `website.yml` to use container v0.2 instead of v0.1.

**Comment by Polarolouis** [comment]
Sorry I missed the existence of `pr_actions.yml`and the fact that simChef was already in container.

I updated `website.yml` to use container v0.2. 

Wouldn't it be clearer to have all additional packages specified in the website.yml ? 
Or to update the container image to add them at image build ?

**Comment by astamm** [comment]
You are right in principle.

The reasons of the current setup is that everyone can add packages to `pr_actions.yml` and therefore make sure that corresponding `.qmd`s do not fail to compile while I think that the docker container has to be rebuilt by a single person (@MarieEtienne I think) each time a new package is required.

The case of non-CRAN packages is subtle because token configuration in the GitHub action does not behave well, making the run of `remotes::install_github()` fail. We therefore add those directly into the container.

**Comment by astamm** [comment]
I modified the GHA scripts to install all required dependencies. @Polarolouis, do you want to merge that once the checks are done?

**Comment by Polarolouis** [comment]
Thank you @astamm, I just resolved a conflict and once the checks have passed I'll merge into main. :smile:

**Pull request merged**
